/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aispeech_audio_CpldAudioRecorder */

#ifndef _Included_com_aispeech_audio_CpldAudioRecorder
#define _Included_com_aispeech_audio_CpldAudioRecorder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aispeech_audio_CpldAudioRecorder
 * Method:    native_setup
 * Signature: (IIIII)I
 */
static jint JNICALL Java_com_aispeech_audio_CpldAudioRecorder_native_1setup
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     com_aispeech_audio_CpldAudioRecorder
 * Method:    native_release
 * Signature: ()V
 */
static void JNICALL Java_com_aispeech_audio_CpldAudioRecorder_native_1release
  (JNIEnv *, jclass);

/*
 * Class:     com_aispeech_audio_CpldAudioRecorder
 * Method:    native_read
 * Signature: ([BII)I
 */
static jint JNICALL Java_com_aispeech_audio_CpldAudioRecorder_native_1read
  (JNIEnv *, jclass, jbyteArray, jint, jint);

/*
 * Class:     com_aispeech_audio_CpldAudioRecorder
 * Method:    native_set_channels_gain
 * Signature: ([BI)I
 */
static jint JNICALL Java_com_aispeech_audio_CpldAudioRecorder_native_1set_1channels_1gain
  (JNIEnv *, jclass, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
